### ISSUE TITLE
Headings in posts/comments are too big

### ISSUE THREAD

**Issue by maximevaillancourt** [maximevaillancourt/change-my-view-new-tab#3]
Since the post/comment content HTML comes straight from Reddit *and* gets CSS applied from the extension itself, this can lead to formatting issues. For example, the heading in the post shown below is bigger than the post title itself:

![2018-02-25-095925_697x664_scrot](https://user-images.githubusercontent.com/8457808/36642796-a04af0ea-1a12-11e8-88cf-4e13da35db10.png)

Possible solution: posts/comments could be wrapped in a class which reduces the size of headings, something like this:

```css
.reddit-content h1,
.reddit-content h2,
.reddit-content h3,
.reddit-content h4,
.reddit-content h5,
.reddit-content h6 {
  font-size: 0.9em;
}
```
